language: php

php:
  - 7.0
  - 7.1
  - 7.2

env:
  - DB=sqlite

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

services:
  - redis-server

matrix:
  include:
    - php: 7.0
      env: DB=mysql
      services:
        - redis-server
        - mysql
    - php: 7.0
      env: DB=maria
      addons:
        mariadb: 10.1
    - php: 7.0
      env: DB=pgsql
      addons:
        postgresql: "9.3"
      services:
        - redis-server
        - postgresql

before_install:
  - phpenv config-rm xdebug.ini

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
    - cp .env.example .env
    - sed -i 's/APP_ENV=production/APP_ENV=local/g' .env
    - make travis
    - php artisan key:generate --no-interaction
    - php artisan migrate --seed --env="testing"
    - php vendor/bin/codecept build
    - make file-permission
    - sleep 5
    - php -S 127.0.0.1:8000 -t public/ 2>&1 >/dev/null &

script: 
  - make cs
  - php vendor/bin/codecept run

after_script:
  - cat $TRAVIS_BUILD_DIR/storage/logs/*.log
