# 考虑到大家对于安装部署 Piplin 还有诸多问题，所以此版本偏向于教程展现部署过程，而非为生产部署优化
version: "3"
services:
  web:
    build: ./web
    volumes:
    - ./web/supervisor/piplin.conf:/etc/supervisor/conf.d/piplin.conf
    - ./web/nginx/piplin.template:/etc/nginx/conf.d/default.conf
    - ./web/env:/var/www/piplin/.env
    - piplin-storage:/var/www/piplin/storage
    ports:
    - "80:80"
    links:
    - 'mysql:piplin-mysql'
    - 'redis:piplin-redis'

  mysql:
    image: mysql:5.6
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_DATABASE: piplin
      MYSQL_USER: piplin
      MYSQL_PASSWORD: piplinpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - piplin-mysql:/var/lib/mysql
    expose:
      - "3306"

  redis:
    image: redis:3.2
    expose:
      - "6379"
    volumes:
      - piplin-redis:/data

volumes:
  piplin-storage:
  piplin-mysql:
  piplin-redis: